import React from "react";
import Head from "next/head";

const Slug = ({ data }) => {
    if (data.status && data.status == 404) {
        return <h1 className="mt-5 pt-5 mx-3">No country exist</h1>;
    } else {
        let [cdata] = data;
        return (
            <section className="mt-5">
                <Head>
                    <title>{cdata.name.common}</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="d-flex justify-content-center pt-5">
                    <img className="w-50 m-auto" src={cdata.flags.png} />
                </div>
                <div className="mx-3 mt-3">
                    <h1>{cdata.name.common}</h1>
                    <p className="m-0 p-0">
                        <span className="fw-bold">Population:</span>{" "}
                        {cdata.population}
                    </p>
                    <p className="m-0 p-0">
                        <span className="fw-bold">Area:</span> {cdata.area}
                    </p>
                    <p className="m-0 p-0">
                        <span className="fw-bold">Region:</span> {cdata.region}
                    </p>
                    <p className="m-0 p-0">
                        <span className="fw-bold">Capital:</span>{" "}
                        {cdata.capital}
                    </p>
                    <p className="m-0 p-0">
                        <span className="fw-bold">TimeZone:</span>{" "}
                        {cdata.timezones}
                    </p>
                </div>
            </section>
        );
    }
};

export async function getServerSideProps(context) {
    const slug = context.query.slug;
    let data = await fetch(`https://restcountries.com/v3.1/name/${slug}`);
    data = await data.json();

    return {
        props: { data }, // will be passed to the page component as props
    };
}
export default Slug;
