import React, { useEffect } from "react";
import "bootstrap/dist/css/bootstrap.css";
import Head from "next/head";
import CountryCard from "../components/CountryCard";

const Home = (props) => {
    const CountryCardRender = () =>
        props.data.map((item, index) => {
            return (
                <div key={index} className="col-md-3">
                    <CountryCard item={item} />
                </div>
            );
        });
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section id="country-cards">
                <div className="row mx-0 mt-5 g-4">{CountryCardRender()}</div>
            </section>
        </div>
    );
};
export async function getStaticProps(context) {
    let data = await fetch("https://restcountries.com/v3.1/all");
    data = await data.json();
    data = await data.slice(0, 12);
    return {
        props: { data }, // will be passed to the page component as props
    };
}
export default Home;
